# Generated by Django 5.1.2 on 2024-10-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_image_remove_case_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
